# Generated by Django 5.1.1 on 2024-10-08 06:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_user_delete_item'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
