# Generated by Django 5.1.1 on 2024-11-05 03:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat_app', '0002_remove_chatmessage_text_chatmessage_gemini_output_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatroom',
            name='user',
        ),
        migrations.DeleteModel(
            name='ChatMessage',
        ),
        migrations.DeleteModel(
            name='ChatRoom',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
