# Generated by Django 5.1.1 on 2024-11-08 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat_app', '0004_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_active',
        ),
    ]
