# Generated by Django 5.1.1 on 2024-11-09 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat_app', '0005_remove_user_is_active'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chatroom',
            old_name='user',
            new_name='user_id',
        ),
    ]
