# Generated by Django 5.1.1 on 2024-11-24 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_app', '0008_user_groups_user_is_active_user_is_admin_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatroom',
            name='topic',
            field=models.CharField(choices=[('학교정보', '학교정보'), ('예상문제', '예상문제')], max_length=50),
        ),
    ]
