# Generated by Django 5.1.1 on 2024-11-24 09:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_app', '0009_alter_chatroom_topic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatmessage',
            name='chatroom_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chat_app.chatroom'),
        ),
        migrations.AlterField(
            model_name='chatroom',
            name='topic',
            field=models.CharField(choices=[('school_info', '학교정보'), ('textbook', '예상문제')], max_length=50),
        ),
    ]
