# Generated by Django 5.1.1 on 2024-11-26 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_app', '0010_alter_chatmessage_chatroom_id_alter_chatroom_topic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='content',
            field=models.TextField(),
        ),
    ]
