# Generated by Django 5.1.1 on 2024-12-07 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_app', '0011_alter_file_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatroom',
            name='topic',
            field=models.CharField(choices=[('school_info', '학교정보'), ('textbook', '예상문제'), ('KnuIn', '차세대')], max_length=50),
        ),
    ]
